### ISSUE TITLE
Suggested Changes for SSP

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#271]
- [x] Units.hs: Update variable names of `UnitalChunks` in Units.hs to be more descriptive
- [ ] Body.hs: look into adding the **Derivation** blocks of text (and equations) between Instance Models and Data Definitions
- [x] Body.hs: replace `+:+`s with `,` wherever `foldlSP` is used (i.e. `s4_2_5_p2` and `s4_2_5_p3`)
- [x] Body.hs: Choose either the variable name `s5_1_table` or `table_inputdata` for SSP's table under **R1**, since `s5_1_table = table_inputdata`
- [x] Update `README.md` file to summarize purposes of newer files (e.g. IMods.hs, GenDefs.hs, TMods, DataDefs.hs)
### @AKM11 's additions
- [x] TMods.hs/GenDefs.hs/Modules.hs/Body.hs: Some of the descriptions employ the `foldSent []` command while others employ `+:+`.  Would recommend shifting entirely to the use of `foldSent []` for Sentence/ Paragraph construction.

- [x] Units.hs: If possible, differentiate between the word and definition of each term and add them to their respective sections (as pointed out by the FIXME).  This will likely require a lot of adjustment in other parts of the code but it should still be done. (duplicate of #227)

- [x] IMods.hs: The lines of code in this file are rather long and could probably be shortened.  As previously mentioned (#274) the average line length should be about 80 characters long.

- [x] Log/Stable: The log is getting rather long.  Would recommend updating the stable version of your code.

Part of Issue #269.

**Comment by njericha** [comment]
did the first one here 62ccfecd9de431ffdb675723b9f959423aff3e00

**Comment by njericha** [comment]
5773da63d0042d298d501f5e992fcc3f71b3c3f1 to fix the last one

**Comment by AKM11** [comment]
Since SSP only had one person reviewing it, it was suggested that someone else review its code.  Here are some suggestions on some things that can be adjusted.  Again, if any of these points are unattainable or unnecessary, feel free to disagree with them.

- [ ] TMods.hs/GenDefs.hs/Modules.hs/Body.hs: Some of the descriptions employ the `foldSent []` command while others employ `+:+`.  Would recommend shifting entirely to the use of `foldSent []` for Sentence/ Paragraph construction.

- [ ] Units.hs: If possible, differentiate between the word and definition of each term and add them to their respective sections (as pointed out by the FIXME).  This will likely require a lot of adjustment in other parts of the code but it should still be done.

- [ ] IMods.hs: The lines of code in this file are rather long and could probably be shortened.  As previously mentioned (#274) the average line length should be about 80 characters long.

- [ ] Log/Stable: The log is getting rather long.  Would recommend updating the stable version of your code.

Part of issue #269

**Comment by njericha** [comment]
9b75361843e46f505d27549526ebd06d496c77b5 to fix Aaron's last comment

**Comment by AKM11** [comment]
As of commit 73b30e613dbee5655986a73468a9f9e0a134596a, SSP shows both the term and definition in its symbol description.  Separating the description from the term in Unit.hs is now feasible.

**Comment by njericha** [comment]
0c8c5767ba7b4cdbc4b4357dd6871c40d844f226

**Comment by njericha** [comment]
9a825b6441d85da88ca4d1942b43bc73d6909ce3 and this is for using foldSent
